version: 2
jobs:
  build:
    working_directory: ~/collection-words
    docker:
      - image: circleci/python:3.9.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install gunicorn
            pip install pytest
            pip install flask
            pip install requests
            pip install bs4
            pip install janome
            pip install nltk
            pip install urllib3
            pip install certifi
            
      - run:
          command: |
            . venv/bin/activate
            pytest src/test.py
      - store_artifacts:
          path: test_results
          destination: tr